name: chat_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 2.6.1
  google_sign_in: 5.4.4
  firebase_auth: 4.2.8
  introduction_screen: 3.1.6
  lottie: 2.2.0
  flutter_screenutil: 5.6.1
  hexcolor: 3.0.1
  google_fonts: 4.0.3
  avatar_glow: 2.0.2
  iconly: 1.0.1
  iconsax: 0.0.8
  emoji_picker_flutter: 1.5.2
  get_storage: 2.0.3
  cloud_firestore: 4.4.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/logo/
    - assets/lottie/
    - assets/models/
  uses-material-design: true

